# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20151216_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
