# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20150601_1513'),
        ('courses', '0004_auto_20151216_1849'),
    ]

    operations = [
    ]
