# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_make_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='make',
            old_name='name',
            new_name='make_name',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='name',
            new_name='model_name',
        ),
    ]
