# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 01:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20160326_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 3, 1, 32, 20, 507196, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 3, 1, 32, 27, 978114, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
