# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ip_address',
            field=models.CharField(default='ABC', max_length=120),
        ),
    ]
