# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0003_auto_20160424_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='Default Value', max_length=120),
        ),
        migrations.AlterField(
            model_name='join',
            name='ip_address',
            field=models.CharField(default='Default Value', max_length=120),
        ),
    ]
